// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package mpt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersistNode struct {
	// Types that are valid to be assigned to Content:
	//	*PersistNode_Full
	//	*PersistNode_Short
	//	*PersistNode_Value
	Content              isPersistNode_Content `protobuf_oneof:"Content"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PersistNode) Reset()         { *m = PersistNode{} }
func (m *PersistNode) String() string { return proto.CompactTextString(m) }
func (*PersistNode) ProtoMessage()    {}
func (*PersistNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *PersistNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistNode.Unmarshal(m, b)
}
func (m *PersistNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistNode.Marshal(b, m, deterministic)
}
func (m *PersistNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistNode.Merge(m, src)
}
func (m *PersistNode) XXX_Size() int {
	return xxx_messageInfo_PersistNode.Size(m)
}
func (m *PersistNode) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistNode.DiscardUnknown(m)
}

var xxx_messageInfo_PersistNode proto.InternalMessageInfo

type isPersistNode_Content interface {
	isPersistNode_Content()
}

type PersistNode_Full struct {
	Full *PersistFullNode `protobuf:"bytes,1,opt,name=full,proto3,oneof"`
}

type PersistNode_Short struct {
	Short *PersistShortNode `protobuf:"bytes,2,opt,name=short,proto3,oneof"`
}

type PersistNode_Value struct {
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3,oneof"`
}

func (*PersistNode_Full) isPersistNode_Content() {}

func (*PersistNode_Short) isPersistNode_Content() {}

func (*PersistNode_Value) isPersistNode_Content() {}

func (m *PersistNode) GetContent() isPersistNode_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PersistNode) GetFull() *PersistFullNode {
	if x, ok := m.GetContent().(*PersistNode_Full); ok {
		return x.Full
	}
	return nil
}

func (m *PersistNode) GetShort() *PersistShortNode {
	if x, ok := m.GetContent().(*PersistNode_Short); ok {
		return x.Short
	}
	return nil
}

func (m *PersistNode) GetValue() []byte {
	if x, ok := m.GetContent().(*PersistNode_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PersistNode) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PersistNode_Full)(nil),
		(*PersistNode_Short)(nil),
		(*PersistNode_Value)(nil),
	}
}

type PersistFullNode struct {
	Children             [][]byte `protobuf:"bytes,1,rep,name=Children,proto3" json:"Children,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersistFullNode) Reset()         { *m = PersistFullNode{} }
func (m *PersistFullNode) String() string { return proto.CompactTextString(m) }
func (*PersistFullNode) ProtoMessage()    {}
func (*PersistFullNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1}
}

func (m *PersistFullNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistFullNode.Unmarshal(m, b)
}
func (m *PersistFullNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistFullNode.Marshal(b, m, deterministic)
}
func (m *PersistFullNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistFullNode.Merge(m, src)
}
func (m *PersistFullNode) XXX_Size() int {
	return xxx_messageInfo_PersistFullNode.Size(m)
}
func (m *PersistFullNode) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistFullNode.DiscardUnknown(m)
}

var xxx_messageInfo_PersistFullNode proto.InternalMessageInfo

func (m *PersistFullNode) GetChildren() [][]byte {
	if m != nil {
		return m.Children
	}
	return nil
}

type PersistShortNode struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersistShortNode) Reset()         { *m = PersistShortNode{} }
func (m *PersistShortNode) String() string { return proto.CompactTextString(m) }
func (*PersistShortNode) ProtoMessage()    {}
func (*PersistShortNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{2}
}

func (m *PersistShortNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersistShortNode.Unmarshal(m, b)
}
func (m *PersistShortNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersistShortNode.Marshal(b, m, deterministic)
}
func (m *PersistShortNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersistShortNode.Merge(m, src)
}
func (m *PersistShortNode) XXX_Size() int {
	return xxx_messageInfo_PersistShortNode.Size(m)
}
func (m *PersistShortNode) XXX_DiscardUnknown() {
	xxx_messageInfo_PersistShortNode.DiscardUnknown(m)
}

var xxx_messageInfo_PersistShortNode proto.InternalMessageInfo

func (m *PersistShortNode) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PersistShortNode) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*PersistNode)(nil), "mpt.PersistNode")
	proto.RegisterType((*PersistFullNode)(nil), "mpt.PersistFullNode")
	proto.RegisterType((*PersistShortNode)(nil), "mpt.PersistShortNode")
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059) }

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xa9, 0x2c, 0x48,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x28, 0x51, 0xea, 0x66, 0xe4, 0xe2,
	0x0e, 0x48, 0x2d, 0x2a, 0xce, 0x2c, 0x2e, 0xf1, 0xcb, 0x4f, 0x49, 0x15, 0xd2, 0xe2, 0x62, 0x49,
	0x2b, 0xcd, 0xc9, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd1, 0xcb, 0x2d, 0x28, 0xd1,
	0x83, 0xca, 0xbb, 0x95, 0xe6, 0xe4, 0x80, 0xd4, 0x78, 0x30, 0x04, 0x81, 0xd5, 0x08, 0xe9, 0x72,
	0xb1, 0x16, 0x67, 0xe4, 0x17, 0x95, 0x48, 0x30, 0x81, 0x15, 0x8b, 0x22, 0x2b, 0x0e, 0x06, 0x49,
	0x40, 0x55, 0x43, 0x54, 0x09, 0x89, 0x71, 0xb1, 0x96, 0x25, 0xe6, 0x94, 0xa6, 0x4a, 0x30, 0x2b,
	0x30, 0x6a, 0xf0, 0x80, 0xc4, 0xc1, 0x5c, 0x27, 0x4e, 0x2e, 0x76, 0xe7, 0xfc, 0xbc, 0x92, 0xd4,
	0xbc, 0x12, 0x25, 0x5d, 0x2e, 0x7e, 0x34, 0xcb, 0x84, 0xa4, 0xb8, 0x38, 0x9c, 0x33, 0x32, 0x73,
	0x52, 0x8a, 0x52, 0xf3, 0x24, 0x18, 0x15, 0x98, 0x35, 0x78, 0x82, 0xe0, 0x7c, 0x25, 0x2b, 0x2e,
	0x01, 0x74, 0xeb, 0x84, 0x04, 0xb8, 0x98, 0xbd, 0x53, 0x2b, 0xc1, 0xee, 0xe7, 0x09, 0x02, 0x31,
	0x85, 0x44, 0x60, 0xf6, 0x32, 0x81, 0xc5, 0x20, 0x9c, 0x24, 0x36, 0x70, 0x20, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x36, 0x46, 0xaa, 0x5f, 0x12, 0x01, 0x00, 0x00,
}
